### ISSUE TITLE
SALT

### ISSUE THREAD

**Issue by afterbit01** [mervick/aes-everywhere-java#1]
Hi,
great job mervick!.. just one question .. is it recommended to change the value ("Salted__") of the var. SALTED in AbstractAes256.java in something more "safe"?

protected static final byte[] SALTED = "Salted__".getBytes(US_ASCII);

thanks!

**Comment by mervick** [comment]
Hello.
I use that because openssl AES by default adds this "Salted__" string for detect salted encrypted strings in the decoding mode, for example:
```sh
~ $  echo -n "TEXT" | openssl enc -aes-256-cbc -md md5 -a -A -pass "pass:PASSWORD" | base64 -d

Salted__,-�6E�hU&
                 ���
                    �Vf▒��\
```

Without this "Salted__" string openssl does not recognize salt and can't decrypt.
So it's not my innovation, it's by a standard, and it's absolutely safe, because the main point of this is salt, which is always random and mixed with password, this makes encrypted string each time different and impossible to detect even very simple passwords.

**Comment by mervick** [comment]
I can't change that string because `AES Everywhere` implements OpenSSL compatible cryptography, so all strings encrypted with `AES Everywhere` in any language can be decrypted in OpenSSL CLI and vice versa.

**Comment by afterbit01** [comment]
ok thanks!
